id: perverse_incentive
name: Perverse Incentive
intent: Look at their incentives from their perspective. Change the incentives. The behavior will follow. (Unless you screw up the incentives, which is easy to do.)
triggers:
- People are working so as to sabotage progress towa...
preconditions:
- People are working so as to sabotage progress towards a desired outcome.
voice:
  style: analytical
  tone: helpful
questions:
- id: q_0
  prompt: Hang on. They are doing what they are incentivized to do. Make quota or else?
- id: q_1
  prompt: I’ll make quota. So would you if you were in their position.?
- id: q_2
  prompt: ” Then think about how to change the incentive system.?
scaffold:
  guidance: 'The user is facing this pattern: People are working so as to sabotage progress towards a desired outcome..

    Your goal is to help them apply this transformation: Look at their incentives from their perspective. Change the incentives. The behavior will follow. (Unless you screw up the incentives, which is easy to do.).


    Context:

    Sales people are poaching sales from other regions, resulting in lower overall sales for the company. Bad sales people!

    Hang on. They are doing what they are incentivized to do. Make quota or else? I’ll make quota. So would you if you were in their position.

    Identifying perverse incentives requires thinking, just for a moment, the worst of people. “What would I do if I was a greedy, venal, short-term, selfish person facing those incentives?” Then think about how to change the incentive system.

    N...'
output_template: 'Pattern: People are working so as to sabotage progress towards a desired outcome.

  Transformation: Look at their incentives from their perspective. Change the incentives. The behavior will follow. (Unless you screw up the incentives, which is easy to do.)


  Analysis:

  {analysis}


  Suggested Next Step:

  {next_step}'
examples: []
pitfalls: []
