id: reduce_variance
name: Reduce Variance
intent: how would you reduce the variance in your work, even if that would “take longer”?
triggers:
- you aren’t responding to change in time. Everyone ...
preconditions:
- you aren’t responding to change in time. Everyone is pushing to get more done.
voice:
  style: analytical
  tone: helpful
questions:
- id: situation
  prompt: What is the situation you are facing?
scaffold:
  guidance: 'The user is facing this pattern: you aren’t responding to change in time. Everyone is pushing to get more done..

    Your goal is to help them apply this transformation: how would you reduce the variance in your work, even if that would “take longer”?.


    Context:

    In Reduce Utilization we saw that pushing utilization too high impedes the ability to respond to new work. The other implication of Kingman’s Formula is that as variance increases the lead time for new work also rises to infinity. Reducing variance “magically” makes us more responsive.

    Developer testing, for example TDD, reduces variance. When the programmer says the work is done, it’s (more likely) to be done, even though the programmer seems to be doing more work (whether it’s actually more wo...'
output_template: 'Pattern: you aren’t responding to change in time. Everyone is pushing to get more done.

  Transformation: how would you reduce the variance in your work, even if that would “take longer”?


  Analysis:

  {analysis}


  Suggested Next Step:

  {next_step}'
examples: []
pitfalls: []
